<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\DocumentAssistant.Application\DocumentAssistant.Application.csproj" />
    <ProjectReference Include="..\DocumentAssistant.Domain\DocumentAssistant.Domain.csproj" />
    <ProjectReference Include="..\DocumentAssistant.Shared\DocumentAssistant.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.SemanticKernel" Version="1.78.0" />
    <PackageReference Include="Microsoft.SemanticKernel.Connectors.OpenAI" Version="1.78.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
